### ISSUE TITLE
Why batch_size = 1 throws an error? 

### ISSUE THREAD

**Issue by arasharchor** [liulei01/DRBox#17]
Hi, 
I wanted to try batch_size 1 rather than 64 because I have only one image at a time and with 64 it takes much longer. However, when I change batch size to 1 both in the deploy.py and deploy.prototxt, I see the following error:

`inputdata[count] = subimage
IndexError: index 1 is out of bounds for axis 0 with size 1`

**Comment by arasharchor** [comment]
thanks I figured it out.

**Comment by keck91** [comment]
Could you share your insights?

**Comment by Viktor-Paul** [comment]
> thanks I figured it out.

Could you share your insights?

**Comment by Viktor-Paul** [comment]
> Could you share your insights?

Did you finally solve this problem?
