### ISSUE TITLE
the large files of RSobject uncompressed failed,anybody konws why?

### ISSUE THREAD

**Issue by 646677064** [liulei01/DRBox#22]
cat data.tar.gz0* >>data.tar.gz
tar -zxvf data.tar.gz

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

**Comment by 646677064** [comment]
only a part of files uncompressed success, not success for all of the data.tar.gz

**Comment by 646677064** [comment]
the small data is ok!!!

**Comment by lijain** [comment]
数据不对，可以给一份正确的数据？1632401541@qq.com

**Comment by mindmad** [comment]
@lijain  can you send me also the correct data
