### ISSUE TITLE
dataset format

### ISSUE THREAD

**Issue by FSet89** [liulei01/DRBox#23]
The "smaller" dataset is very large and can't be directly downloaded. Could you at least provide some guidelines on how to build our own dataset?

**Comment by 646677064** [comment]
the small data is ok!!!

**Comment by zdgithub** [comment]
> the small data is ok!!!

Hi, I download the small data, but the files format `.tar.gz00` cann't be unzipped.
How did you unzip them? Thank you

**Comment by mindmad** [comment]
@zdgithub  have you solved the problem 
I too can't unzip them

**Comment by mindmad** [comment]
> the small data is ok!!!

@646677064  how did you unzip them

**Comment by mindmad** [comment]
@zdgithub 
to unzip them you need to do these command 

cat data.tar.gz* >>data.tar.gz
tar -zxvf data.tar.gz
