### ISSUE TITLE
Issue training custom dataset

### ISSUE THREAD

**Issue by FSet89** [liulei01/DRBox#24]
I made a very small dataset just to test the framework. I placed the files in data/MyDataset/train_data (jpg files and .jpg.rbox files with same name). The I created the trainval.txt file in data/MyDataset and I copied create_data.sh in the same folder. I ran the script and two MDB files were generated (data and lock). Finally, I created a script in examples/rbox just like the others and I ran it, but I got the following error:

```
I0828 15:01:18.558032 26291 base_data_layer.cpp:32] DataLayerSetUp:
I0828 15:01:18.559165 26298 db_lmdb.cpp:35] Opened lmdb examples/MyDataset/MyDataset_trainval_lmdb
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
*** Aborted at 1535461278 (unix time) try "date -d @1535461278" if you are using GNU date ***
```

Did I do something wrong?

**Comment by FSet89** [comment]
I forgot to resize the original images.

**Comment by ruinianxu** [comment]
@FSetragno 
Hi FSetragno,
Could you please let me know the fromat of trainval.txt? I can't download the original dataset. 
Thanks

**Comment by FSet89** [comment]
Hi,
each row is like this (note the single space as separator):
filename.jpg filename.jpg.rbox

**Comment by ruinianxu** [comment]
@FSetragno 
Got it! Thank you so much for your help.
